---
# core/tasks/main.yml
# spark ~ core >> base system stub // %DORMANT%
- { ansible.builtin.include_tasks: packages.yml, tags: [base, packages] }
- { ansible.builtin.include_tasks: config.yml,   tags: [base, config]   }
