# dotfiles/shell/zsh/p10k.zsh
# =============================================================================
# RaBbLE — Powerlevel10k prompt configuration
# Generated by `p10k configure`, then hand-tuned for RaBbLE palette.
# Run `p10k configure` to regenerate interactively, then copy back to dotfiles.
# =============================================================================

# Temporarily change options
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
    emulate -L zsh -o extended_glob

    # Unset all configuration options
    unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

    # Zsh >= 5.1 required
    autoload -Uz is-at-least && is-at-least 5.1 || return

    # ── Prompt elements ───────────────────────────────────────────────────────
    typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
        # os_icon           # uncomment for OS icon
        dir                 # current directory
        vcs                 # git status
        context             # user@host (only when SSH or root)
        virtualenv          # python venv
        nodenv              # node version
        goenv               # go version
        newline
        prompt_char         # ❯ / ✗ prompt character
    )

    typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
        status              # exit code of previous command
        command_execution_time  # duration of last command
        background_jobs     # number of background jobs
        direnv              # direnv status
        asdf                # asdf version manager
        # time              # uncomment to show clock on right
    )

    # ── Common ────────────────────────────────────────────────────────────────
    typeset -g POWERLEVEL9K_MODE=nerdfont-complete
    typeset -g POWERLEVEL9K_ICON_PADDING=none
    typeset -g POWERLEVEL9K_ICON_BEFORE_CONTENT=
    typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
    typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR=' '
    typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=238
    typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=
    typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=
    typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=

    # ── Prompt char ───────────────────────────────────────────────────────────
    typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=76
    typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=196
    typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
    typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
    typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='V'
    typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='▶'
    typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true
    typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=

    # ── Dir — RaBbLE violet ───────────────────────────────────────────────────
    typeset -g POWERLEVEL9K_DIR_BACKGROUND=17
    typeset -g POWERLEVEL9K_DIR_FOREGROUND=135
    typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=103
    typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=135
    typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
    local anchor_files=(
        .bzr CVS .git .hg .svn .terraform .citc
        package.json .python-version .go-version
        requirements.txt Pipfile .venv
        Dockerfile Makefile
    )
    typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
    typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=
    typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=40
    typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=40
    typeset -g POWERLEVEL9K_DIR_HOME_SYMBOL='~'
    typeset -g POWERLEVEL9K_DIR_PREFIX=

    # ── VCS (git) — RaBbLE teal + palette ────────────────────────────────────
    typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '
    typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
    typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=0
    typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=80
    typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=0
    typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=214
    typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=0
    typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=218
    typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND=0
    typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=196
    typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND=0
    typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=245

    # ── Status ────────────────────────────────────────────────────────────────
    typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true
    typeset -g POWERLEVEL9K_STATUS_OK=false
    typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=70
    typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=0
    typeset -g POWERLEVEL9K_STATUS_ERROR=true
    typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=160
    typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=0
    typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=174
    typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND=0
    typeset -g POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false

    # ── Command execution time ─────────────────────────────────────────────────
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=248
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=0
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'

    # ── Python virtualenv ─────────────────────────────────────────────────────
    typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND=0
    typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=37
    typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false
    typeset -g POWERLEVEL9K_VIRTUALENV_{LEFT,RIGHT}_DELIMITER=

    # ── Context (user@host) — only when SSH or root ───────────────────────────
    typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='%B%F{196}root@%m%f%b'
    typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_TEMPLATE='%F{245}%n%f@%F{135}%m%f'
    typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%F{245}%n%f@%F{135}%m%f'
    typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_CONTENT_EXPANSION=

    # ── Background jobs ───────────────────────────────────────────────────────
    typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false
    typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=0
    typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VISUAL_IDENTIFIER_EXPANSION='⇶'
    typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=70

    # ── Instant prompt ────────────────────────────────────────────────────────
    typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose

    # ── Hot reload ────────────────────────────────────────────────────────────
    (( ! $+functions[p10k] )) || p10k reload
}

# Restore options
(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
