---
# hardware/x64/asus_proart_p16/tasks/main.yml
# spark ~ hardware/asus_proart_p16 >> stub // %DORMANT%
- { ansible.builtin.include_tasks: packages.yml,       tags: [hardware, packages]       }
- { ansible.builtin.include_tasks: amd_gfx.yml,        tags: [hardware, amd_gfx]        }
- { ansible.builtin.include_tasks: nvidia.yml,          tags: [hardware, nvidia]         }
- { ansible.builtin.include_tasks: asusctl.yml,         tags: [hardware, asus]           }
- { ansible.builtin.include_tasks: npu.yml,             tags: [hardware, npu]            }
- { ansible.builtin.include_tasks: xrt.yml,             tags: [hardware, npu, xrt]       }
- { ansible.builtin.include_tasks: audio.yml,           tags: [hardware, audio]          }
- { ansible.builtin.include_tasks: firmware.yml,        tags: [hardware, firmware]       }
- { ansible.builtin.include_tasks: power/asusd.yml,     tags: [hardware, power]          }
- { ansible.builtin.include_tasks: power/supergfxd.yml, tags: [hardware, power]          }
- { ansible.builtin.include_tasks: power/tuned.yml,     tags: [hardware, power]          }
- { ansible.builtin.include_tasks: power/arbitration.yml, tags: [hardware, power]        }
- { ansible.builtin.include_tasks: config.yml,          tags: [hardware, config]         }
