# dotfiles/hyprland/conf.d/animations.conf

animations {
    enabled = true

    bezier = smoothOut,   0.36, 0, 0.66, -0.56
    bezier = smoothIn,    0.25, 1, 0.5,  1
    bezier = overshot,    0.05, 0.9, 0.1, 1.05
    bezier = linear,      1,    1,  1,   1
    bezier = rabble,      0.22, 1, 0.36, 1

    animation = windows,     1, 5,  rabble,   slide
    animation = windowsOut,  1, 4,  smoothOut, slide
    animation = windowsMove, 1, 4,  rabble
    animation = fade,        1, 4,  smoothIn
    animation = fadeOut,     1, 3,  smoothOut
    animation = border,      1, 8,  linear
    animation = borderangle, 1, 30, linear,   loop
    animation = workspaces,  1, 5,  rabble,   slidehoriz
    animation = specialWorkspace, 1, 5, rabble, slidefadehoriz
    animation = layers,      1, 3,  rabble,   slide
}
