---
- name: reload logind
  ansible.builtin.systemd:
    name: systemd-logind
    state: reloaded
  become: true

- name: restart sddm
  ansible.builtin.systemd:
    name: sddm
    state: restarted
  become: true
